name: Build
on: [push, pull_request]

jobs:
    build:
        name: Dub Build (${{ matrix.os }} - ${{ matrix.dc }})
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest]
                dc: [dmd, ldc]
                include:
                    - { os: ubuntu-latest, dc: gdc }
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install D compiler
              uses: dlang-community/setup-dlang@v2
              with:
                  compiler: ${{ matrix.dc }}

            - name: Build
              run: dub build
